global:
  config_version: 3
input:
  type: file
  path: /var/log/syslog
  readall: true
  poll_interval_seconds: 5

imports:
- type: grok_patterns
  dir: /etc/grok/patterns

metrics:
    - type: counter
      name: LogEventCount
      help: Count eq-node events
      match: '%{MONTH} %{MONTHDAY} %{TIME} %{SYSLOGHOST:instance} %{SYSLOGPROG}*\s%{POLKATIME} %{LOGLEVEL:severity} %{GREEDYDATA:message}'
      labels:
        severity: '{{.severity}}'
        instance: '{{.instance}}'

server:
  port: 9110
