---
  - name: Gather facts about service
    service_facts:

  - name: Set node exporter service state var
    debug:
      var: ansible_facts.services["ipsec_exporter.service"]["status"]

  - name: Download and extract archive
    unarchive:
      src: https://github.com/dennisstritzke/ipsec_exporter/releases/download/v0.3.1/ipsec_exporter-v0.3.1.linux-amd64.tar.gz
      dest: /root
      remote_src: yes
    when: ansible_facts.services["ipsec_exporter.service"] is not defined

  - name: Copy binary
    copy:
      src: /root/ipsec_exporter-v0.3.1.linux-amd64
      dest: /usr/local/bin/ipsec_exporter
      remote_src: yes
      mode: '0755'
    when: ansible_facts.services["ipsec_exporter.service"] is not defined

  - name: Make systemd unit
    template: src=ipsec_exporter.service dest=/etc/systemd/system/ipsec_exporter.service
    when: ansible_facts.services["ipsec_exporter.service"] is not defined
      
  - name: Firewall - allow port UBUNTU
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      to_port: 9536
    when: ansible_facts.services["ipsec_exporter.service"] is not defined and hostvars[inventory_hostname].ansible_distribution == 'Ubuntu'

  - name: Firewall - allow port CENTOS
    firewalld:
      port: 9536/tcp
      permanent: true
      state: enabled
    when: ansible_facts.services["ipsec_exporter.service"] is not defined and hostvars[inventory_hostname].ansible_distribution == 'CentOS'


  - name: Start node exporter daemon
    systemd:
      daemon_reload: yes
      name: ipsec_exporter.service
      enabled: yes
      state: started
    when: ansible_facts.services["ipsec_exporter.service"] is not defined
