---
  - name: Gather facts about service
    service_facts:

  - name: Set unifi exporter service state var
    debug:
      var: ansible_facts.services["unifi_exporter.service"]["status"]

  - name: Copy binary
    get_url:
      url: https://github.com/mdlayher/unifi_exporter/releases/download/0.4.0/unifi_exporter
      dest: /usr/local/bin/unifi_exporter
      mode: 0755
    when: ansible_facts.services["unifi_exporter.service"] is not defined

  - name: Make systemd unit
    template: src=unifi_exporter.service dest=/etc/systemd/system/unifi_exporter.service
    when: ansible_facts.services["ipsec_exporter.service"] is not defined
      
  - name: Firewall - allow port UBUNTU
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      to_port: 9130
    when: ansible_facts.services["unifi_exporter.service"] is not defined and hostvars[inventory_hostname].ansible_distribution == 'Ubuntu'

  - name: Firewall - allow port CENTOS
    firewalld:
      port: 9130/tcp
      permanent: true
      state: enabled
    when: ansible_facts.services["unifi_exporter.service"] is not defined and hostvars[inventory_hostname].ansible_distribution == 'CentOS'


  - name: Start node exporter daemon
    systemd:
      daemon_reload: yes
      name: unifi_exporter.service
      enabled: yes
      state: started
    when: ansible_facts.services["unifi_exporter.service"] is not defined
