---

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify:
    - Nginx status

- name: Copy files from templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "nginx.conf.j2", dest: "/etc/nginx/nginx.conf" }
  notify:
    - Reload nginx
